
export enum PlumbingEnum{
	TAP = <any>"TAP",
	WASH_BASIN = <any>"WASH BASIN",
	KITCHEN_SINK = <any>"KITCHEN SINK",
	WESTERN_TOILET = <any>"WESTERN TOILET",
	FLUSH_TANK = <any>"FLUSH TANK",
	INDIAN_TOILET = <any>"INDIAN TOILET",
	TOILET_JET = <any>"TOILET JET",
	SHOWER = <any>"SHOWER",
	PIPELINE = <any>"PIPELINE",
	PUMPS = <any>"PUMPS",
	OTHERS = <any>"OTHERS",
}

export enum ElectricalEnum{
	CEILING_FAN = <any>"CEILING FAN",
	EXHAUST_FAN = <any>"EXHAUST FAN",
	STAND_FAN = <any>"STAND FAN",
	MCB = <any>"MAIN CONTROL BOARD",
	NEW_ELECTRIC_POINT = <any>"NEW ELECTRIC POINT",
	THREE_PHASE_PANNEL_BOARD = <any>"THREE PHASE PANNEL BOARD",
	WIRING = <any> "WIRING",
	TUBE_LIGHT_WITH_PANNEL = <any>"TUBE LIGHT WITH PANNEL",
	FANCY_LIGHT = <any>"FANCY LIGHT",
	SOCKET_AND_HOLDERS = <any>"SOCKETS AND HOLDERS",
	INVERTER = <any>"INVERTER",
	OTHERS = <any>"OTHERS",
}

export enum CarpentryEnum{
	DOOR_STOPPER = <any>"DOOR STOPPER",
	HANDLE = <any>"HANDLE",
	DOOR_CHAIN = <any> "DOOR CHAIN",
	DOOR_LATCH = <any> "DOOR LATCH",
	HINGES = <any> "HINGES",
	DOOR_PEEPHOLE = <any>"DOOR PEEPHOLE",
	LOCK = <any>"LOCK",
	LAMINATION = <any>"LAMINATION",
	WOODEN_PARTITION = <any>"WOODEN PARTITION",
	MESH = <any>"MESH",
	SOFA = <any>"SOFA",
	WOODEN_CHAIR = <any>"WOODEN_CHAIR",
	BED = <any>"BED",
	FURNITURE_REPAIR = <any> "FURNITURE REPAIR",
	OTHERS = <any>"OTHERS"
}

export enum AppliancesEnum{
	AC_SERVICE = <any> "AC SERVICE",
	AC_GAS_FILL = <any> "AC GAS FILL",
	AC_INSTALLATION = <any> "AC INSTALLATION",
	AC_OTHER_REPAIR = <any> "OTHER REPAIR",
	REFRIGERATOR_SERVICE = <any>"REFRIGERATOR SERVICE",
	REFRIGERATOR_REPAIR = <any>"REFRIGERATOR REPAIR",
	WASHING_MACHINE_SERVICE = <any>"WASHING MACHINE SERVICE",
	WASHING_MACHINE_REPAIR = <any> "WASHING MACHINE REPAIR",
	MICROWAVE_OVEN_REPAIR = <any> "MICROWAVE OVEN REPAIR",
	WATER_PURIFIER_SERVICE = <any> "WATER PURIFIER SERVICE",
	TV_REPAIR = <any> "TV REPAIR",
	GEYSER_SERVICE = <any> "GEYSER SERVICE",
	OTHERS = <any> "OTHERS"

}

export enum Service{
	PLUMBING = <any> "PLUMBING",
	ELECTRICAL = <any> "ELECTRICAL",
	CARPENTRY = <any> "CARPENTRY",
	APPLIANCES = <any> "APPLIANCES",
	CARS_AND_BIKES = <any> "CARS_AND_BIKES",
	BEAUTY = <any> "BEAUTY",
	BUSINESS_SERVICE = <any> "BUSINESS_SERVICE",
	PERSONAL_SERVICE = <any> "PERSONAL_SERVICE",
	LAUNDARY_IRON = <any> "LAUNDARY_IRON",
	OTHERS = <any> "OTHERS"
}

export enum LaundaryEnum{
	FULL_SHIRT = <any> "FULL SHIRT",
	HALF_SHIRT = <any> "HALF SHIRT",
	TROUSERS = <any> "TROUSERS",
	JEANS = <any> "JEANS",
	KURTA = <any> "KURTA",
	PAIJAMA = <any> "PAIJAMA",
	SHORTS = <any> "SHORTS",
	TRACKSUIT = <any> "TRACKSUIT",
	SUITS = <any> "SUITS",
	SHERWANI = <any> "SHERWANI",
	COAT_BLAZER = <any> "COAT/BLAZER",
	WAIST_COAT = <any> "WAIST COAT",
	DHOTI = <any> "DHOTI",
	SWEATER = <any> "SWEATER",
	SWEATSHIRT = <any> "SWEATSHIRT",
	JACKET_NORMAL = <any> "JACKET NORMAL",
	JACKET_WOOLEN =<any> "JACKET WOOLEN",
	JACKET_LEATHER = <any>"JACKET LEATHER",
	OVERCOAT = <any>"OVERCOAT",
	DUPATTA = <any> "DUPATTA",
	SALWAR_TROUSER = <any> "SALWAR TROUSER",
	LADIES_KURTA = <any> "KURTA",
	SKIRT = <any> "SKIRT",
	SAREE_COTTON = <any> "SAREE COTTON",
	BLOUSE = <any> "BLOUSE",
	WESTERN_TOP = <any> "WESTERN TOP",
	PETTICOAT = <any> "PETTI COAT",
	SAREE_SILK = <any> "SAREE SILK",
	LEHENGA = <any>"LEHENGA",
	WOMEN_GOWN = <any>"WOMEN GOWN",
	MUFFLER = <any>"MUFFLER",
	SHAWL = <any>"SHAWL",
	BEDSHEET_SINGLE = <any>"BEDSHEET SINGLE",
	BEDHSEET_DOUBLE = <any>"BEDSHEET DOUBLE",
	BLANKET = <any>"BLANKET",
	TABLE_CLOTH = <any>"TABLE CLOTH",
	CURTAINS = <any> "CURTAINS",


}

export const CityList: Array<{display_name:string, value:string}> = [
			{
			display_name: "Lucknow",
				value: "LUCKNOW"
			}
		]

export enum StorageKey{
	ADDRESS_KEY = <any> "address"
}

export let ADDRESS_KEY = "address";
export let PHONE_KEY = "phone_number";


